# ==========================================================
# Halmos Web Server Configuration
# ==========================================================

[Network]
# Alamat IP server (Gunakan 0.0.0.0 untuk mendengarkan di semua interface)
# Port 8080, bisa anda ganti sesuai keinginan anda selama port tidak digunakan aplikasi lain
# Biasanya port web server HTTP itu menggunakan port 80
# atau port web server HTTPS itu menggunakan port 443
# Di browser anda bisa mengakses URL http://localhost:8080 atau http://127.0.0.1:8080
server_name = 127.0.0.1
server_port = 8080

[Storage]
# Direktori tempat file HTML/Web disimpan
document_root = /var/www/html/halmos/
# File utama yang dibuka jika folder diakses
default_page = index.html

[Security]
# Batas ukuran request body (Default: 10MB dalam bytes)
max_body_size = 10485760
# Mode aplikasi aman
secure_application = true
#Pembatasan akses true/false
rate_limit_enabled = false
#Jumlah akses maksimal per detik
max_requests_per_sec = 50
keep_alive_timeout = 5

[Backend_PHP]
# Konfigurasi koneksi ke PHP-FPM (FastCGI)
php_server = 127.0.0.1
php_port = 9000

# Konfigurasi koneksi ke Rust-FPM (Spwan-FastCGI)
[Backend_Rust]
rust_ext = .rs
rust_server = 127.0.0.1
rust_port = 9001

# Konfigurasi koneksi ke Python WSGI
[Backend_Python]
python_ext = .py
python_server = 127.0.0.1
python_port = 9002

[Performance]
# Default besar buffer untuk menampung request awal
request_buffer_size = 4096
max_queue_size = 5000
